### ISSUE TITLE
Debian 11 installation problem

### ISSUE THREAD

**Issue by Uzzi** [uhppoted/uhppoted-httpd#10]
Hi, I'm running on debian 11 amd64
these are my step:
apt install git make wget -y

##Install Go
cd /tmp
wget https://golang.org/dl/goxxx.linux-amd64.tar.gz
tar -zxvf goxxx.linux-amd64.tar.gz -C /usr/local/
echo "export PATH=/usr/local/go/bin:${PATH}" | tee /etc/profile.d/go.sh
source /etc/profile.d/go.sh
##Verify
go version

##Install nodejs-npm
apt install nodejs npm -y
##Verify
node -v
npm -v

##Install sass
npm install -g sass

##Install eslint
npm install eslint

##Install eslint-config-standard
npm install eslint-config-standard

then:
cd /opt
git clone https://github.com/uhppoted/uhppoted-httpd.git
cd uhppoted-httpd
make build

This is output:
go fmt ./...
mkdir -p httpd/html/images/default
sass --no-source-map sass/themes/light:httpd/html/css/default
sass --no-source-map sass/themes/light:httpd/html/css/light
sass --no-source-map sass/themes/dark:httpd/html/css/dark
cp httpd/html/images/light/* httpd/html/images/default
npx eslint --fix httpd/html/javascript/*.js

Oops! Something went wrong! :(

ESLint: 8.23.0

ESLint couldn't find the config "standard" to extend from. Please check that the name of the config is correct.

The config "standard" was referenced from the config file in "/opt/uhppoted-httpd/.eslintrc.js".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.

npm ERR! code 2
npm ERR! path /opt/uhppoted-httpd
npm ERR! command failed
npm ERR! command sh -c eslint "--fix" "httpd/html/javascript/cards.js" "httpd/html/javascript/combobox.js" "httpd/html/javascript/controllers.js" "httpd/html/javascript/db.js" "httpd/html/javascript/doors.js" "httpd/html/javascript/events.js" "httpd/html/javascript/groups.js" "httpd/html/javascript/interfaces.js" "httpd/html/javascript/login.js" "httpd/html/javascript/logs.js" "httpd/html/javascript/overview.js" "httpd/html/javascript/password.js" "httpd/html/javascript/schema.js" "httpd/html/javascript/tabular.js" "httpd/html/javascript/timezones.js" "httpd/html/javascript/uhppoted.js" "httpd/html/javascript/users.js"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-02T08_34_59_721Z-debug.log
make: *** [Makefile:48: build] Errore 2

this is /root/.npm/_logs/2022-09-02T08_34_59_721Z-debug.log:
0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/usr/share/nodejs/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'eslint',
0 verbose cli   '--fix',
0 verbose cli   'httpd/html/javascript/cards.js',
0 verbose cli   'httpd/html/javascript/combobox.js',
0 verbose cli   'httpd/html/javascript/controllers.js',
0 verbose cli   'httpd/html/javascript/db.js',
0 verbose cli   'httpd/html/javascript/doors.js',
0 verbose cli   'httpd/html/javascript/events.js',
0 verbose cli   'httpd/html/javascript/groups.js',
0 verbose cli   'httpd/html/javascript/interfaces.js',
0 verbose cli   'httpd/html/javascript/login.js',
0 verbose cli   'httpd/html/javascript/logs.js',
0 verbose cli   'httpd/html/javascript/overview.js',
0 verbose cli   'httpd/html/javascript/password.js',
0 verbose cli   'httpd/html/javascript/schema.js',
0 verbose cli   'httpd/html/javascript/tabular.js',
0 verbose cli   'httpd/html/javascript/timezones.js',
0 verbose cli   'httpd/html/javascript/uhppoted.js',
0 verbose cli   'httpd/html/javascript/users.js'
0 verbose cli ]
1 info using npm@7.5.2
2 info using node@v12.22.12
3 timing config:load:defaults Completed in 3ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 5ms
5 timing config:load:builtin Completed in 5ms
6 timing config:load:cli Completed in 3ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/opt/uhppoted-httpd/.npmrc Completed in 1ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 21ms
19 verbose npm-session 98a6973a40df3d61
20 timing npm:load Completed in 48ms
21 timing command:exec Completed in 1243ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:314:20)
22 verbose stack     at maybeClose (internal/child_process.js:1022:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
23 verbose pkgid uhppoted-httpd@0.6.5
24 verbose cwd /opt/uhppoted-httpd
25 verbose Linux 5.10.0-15-amd64
26 verbose argv "/usr/bin/node" "/usr/share/nodejs/npm/bin/npm-cli.js" "exec" "--" "eslint" "--fix" "httpd/html/javascript/cards.js" "httpd/html/javascript/combobox.js" "httpd/html/javascript/controllers.js" "httpd/html/javascript/db.js" "httpd/html/javascript/doors.js" "httpd/html/javascript/events.js" "httpd/html/javascript/groups.js" "httpd/html/javascript/interfaces.js" "httpd/html/javascript/login.js" "httpd/html/javascript/logs.js" "httpd/html/javascript/overview.js" "httpd/html/javascript/password.js" "httpd/html/javascript/schema.js" "httpd/html/javascript/tabular.js" "httpd/html/javascript/timezones.js" "httpd/html/javascript/uhppoted.js" "httpd/html/javascript/users.js"
27 verbose node v12.22.12
28 verbose npm  v7.5.2
29 error code 2
30 error path /opt/uhppoted-httpd
31 error command failed
32 error command sh -c eslint "--fix" "httpd/html/javascript/cards.js" "httpd/html/javascript/combobox.js" "httpd/html/javascript/controllers.js" "httpd/html/javascript/db.js" "httpd/html/javascript/doors.js" "httpd/html/javascript/events.js" "httpd/html/javascript/groups.js" "httpd/html/javascript/interfaces.js" "httpd/html/javascript/login.js" "httpd/html/javascript/logs.js" "httpd/html/javascript/overview.js" "httpd/html/javascript/password.js" "httpd/html/javascript/schema.js" "httpd/html/javascript/tabular.js" "httpd/html/javascript/timezones.js" "httpd/html/javascript/uhppoted.js" "httpd/html/javascript/users.js"
33 verbose exit 2

Can you help me to fix?
Thank you

**Comment by uhppoted** [comment]
Wow! The default packages on Debian seem to be quite out of date:
```
apt install golang
go version
> go version go1.15.15 linux/amd64

node --version
> v12.22.12

npm --version
> 7.5.2
```

However, that isn't the problem - I replicated your steps and it appears that _eslint_ is for some (probably good) reason using the _eslint-config-standard_ module in the current directory so you need to install it locally in the project directory:
```
cd /opt/uhppoted-httpd
npm install eslint-config-standard
```

That seemed to work so hopefully that fixes the issue for you? 

I'll go dig a bit into the _eslint_ documentation to see if there's an explanation and update the installation steps in the README accordingly.

Just a small note - if you're building it on a fresh system you're going to need to generate all the files needed to run. For the moment the easiest way to do that is (assuming you've already created a _uhppoted_ user):
```
sudo su uhppoted
cd /opt/uhppoted-httpd
./bin/uhppoted-httpd daemonize
./bin/uhppoted-httpd undaemonize
```

**Comment by uhppoted** [comment]
Added note to README to include installing `eslint-config-standard` as a _dev_ dependency.

Closing this issue - feel free to reopen it if you need to .
