### ISSUE TITLE
Implement 'config' command to generate default runtime files

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-httpd#11]
At the moment the easiest way to generate a working configuration for _uhppoted-httpd_ requires the arcane invocation:
```
uhppoted-httpd daemonize
uhppoted-httpd undaemonize
```
which is less than optimal. The same functionality should be available from the application as a _config_ command.

(cf.[Debian 11 installation problem](https://github.com/uhppoted/uhppoted-httpd/issues/10))

**Comment by twystd** [comment]
Feature complete - will be included in release v0.8.3
