### ISSUE TITLE
admin password reset

### ISSUE THREAD

**Issue by Uzzi** [uhppoted/uhppoted-httpd#12]
Hi, how can i reset admin password?
I've lost it!

Thank you

**Comment by uhppoted** [comment]
Hi,

_(you're on Debian if I remember correctly?)_

The 'official' way to do it is to delete the _/var/uhppoted/httpd/system/users.json_ file and then run `uhppoted-httpd daemonize` to recreate it. _daemonize_ will generate a new _admin_ user and and random password without changing any of the other configuration (in theory at least - probably best to make a backup of before doing that). Run `uhppoted-httpd undaemonize` afterwards if you're not running it as a service.

However, the quick and easy way to do it is to just use the _admin_ user from the [quickstart](https://github.com/uhppoted/uhppoted-httpd/blob/master/documentation/starter-kit/var/httpd/system/users.json). Edit _/var/uhppoted/httpd/system/users.json_ and set the _admin_ user salt and password to:
```
      "salt": "4a3d95eec4b94c236824f75ef8305c90",
      "password": "91b228c1595768ff35f8bce555ac089e8e64348e15110fc8ef3653fd4cf7ff67",
```
The password is _uhppoted_. Once you're able to login in again you can change the password to something else from the avatar menu.

I'll add a better recovery mechanism to the TODO list - am sure this is going to be an ongoing pain point.
