### ISSUE TITLE
Cannot access web interface

### ISSUE THREAD

**Issue by MatteoSalviTech** [uhppoted/uhppoted-httpd#21]
Hello! I successfully installed the uhppoted-httpd service which is in running status. Although I cannot access the web interface. What is the default URL to access the web server? Thank you.

**Comment by uhppoted** [comment]
Hi, 

The default installation comes up with only the TLS interface on port 8443 - the URL is https://127.0.0.1:8443 (or https://localhost:8443 if you prefer).

If you want the non-TLS _http_ interface you'll need to update the _uhppoted.conf_ configuration file:
- `/etc/uhppoted/uhppoted.conf` on (Linux)
- `/usr/local/etc/com.github.uhppoted/uhppoted.conf` (MacOS)
- `\ProgramData\uhppoted\uhppoted.conf` (Windows)

Update the following lines under the HTTPD section:
```
# HTTPD
httpd.http.enabled = true
httpd.http.port = 8888
httpd.https.enabled = true
httpd.https.port = 8443
```

and then restart the daemon/service.

**Comment by MatteoSalviTech** [comment]
Thank you so much! I've been able to access the web interface after rebooting the server.

**Comment by uhppoted** [comment]
Oh great :-) !!!
