### ISSUE TITLE
device config does not seem to be honored 

### ISSUE THREAD

**Issue by iKrushYou** [uhppoted/uhppoted-httpd#25]
I have tried setting up via `docker compose` following the steps in the README. I am running into an issue where it seems that the service is not honoring the devices that I have configured in my `uhppoted.conf` file

here is the console out:
```
/opt/uhppoted # /opt/uhppoted/uhppoted-httpd --config /usr/local/etc/uhppoted/uhppoted.conf --console --debug
2024/04/22 13:59:48 uhppoted-httpd service v0.8.8 - Linux (PID 179)
2024/04/22 13:59:48 INFO   HTTPD    HTTPS server starting on port :8443
2024/04/22 13:59:48 INFO   HTTPD    HTTP  server starting on port :8080
2024/04/22 13:59:52 INFO   303986753: refreshing LAN controller status
2024/04/22 13:59:52 INFO   405419896: refreshing LAN controller status
2024/04/22 13:59:53 WARN   not found: no device found for device ID <nil>
2024/04/22 13:59:53 WARN   not found: no device found for device ID <nil>
2024/04/22 13:59:54 WARN   timeout waiting for reply
2024/04/22 13:59:54 WARN   timeout waiting for reply
2024/04/22 13:59:55 WARN   internal server error: error retrieving number of cards from 303986753 (timeout waiting for reply)
2024/04/22 13:59:55 WARN   internal server error: error retrieving number of cards from 405419896 (timeout waiting for reply)
```

but here is my config file 
```
/opt/uhppoted # cat /usr/local/etc/uhppoted/uhppoted.conf
# SYSTEM
# bind.address = 0.0.0.0:0
# broadcast.address = 255.255.255.255:60000
# listen.address = 0.0.0.0:60001

# HTTPD
httpd.html = /usr/local/etc/uhppoted/httpd/html
httpd.http.enabled = true
httpd.http.port = 8080
httpd.https.enabled = true
httpd.https.port = 8443
httpd.tls.ca = /usr/local/etc/uhppoted/httpd/ca.cert
httpd.tls.certificate = /usr/local/etc/uhppoted/httpd/uhppoted.cert
httpd.tls.key = /usr/local/etc/uhppoted/httpd/uhppoted.key
httpd.tls.client.certificates.required = false
; httpd.security.auth = basic
httpd.security.local.db = /usr/local/etc/uhppoted/httpd/auth.json
; httpd.security.cookie.max-age = 24
; httpd.security.login.expiry = 1m
; httpd.security.session.expiry = 60m
; httpd.security.otp.issuer = uhppoted-httpd
; httpd.security.otp.login = allow
; httpd.request.timeout = 5s
httpd.system.interfaces = /usr/local/etc/uhppoted/httpd/system/interfaces.json
httpd.system.controllers = /usr/local/etc/uhppoted/httpd/system/controllers.json
httpd.system.doors = /usr/local/etc/uhppoted/httpd/system/doors.json
httpd.system.groups = /usr/local/etc/uhppoted/httpd/system/groups.json
httpd.system.cards = /usr/local/etc/uhppoted/httpd/system/cards.json
httpd.system.events = /usr/local/etc/uhppoted/httpd/system/events.json
httpd.system.logs = /usr/local/etc/uhppoted/httpd/system/logs.json
httpd.system.users = /usr/local/etc/uhppoted/httpd/system/users.json
httpd.system.history = /usr/local/etc/uhppoted/httpd/system/history.json
; httpd.system.refresh = 30s
; httpd.system.windows.ok = 1m0s
; httpd.system.windows.uncertain = 5m0s
; httpd.system.windows.systime = 5m0s
; httpd.system.windows.expires = 2m0s
httpd.db.rules.acl = /usr/local/etc/uhppoted/httpd/acl.grl
httpd.db.rules.interfaces = /usr/local/etc/uhppoted/httpd/grules/interfaces.grl
httpd.db.rules.controllers = /usr/local/etc/uhppoted/httpd/grules/controllers.grl
httpd.db.rules.doors = /usr/local/etc/uhppoted/httpd/grules/doors.grl
httpd.db.rules.groups = /usr/local/etc/uhppoted/httpd/grules/groups.grl
httpd.db.rules.cards = /usr/local/etc/uhppoted/httpd/grules/cards.grl
httpd.db.rules.users = /usr/local/etc/uhppoted/httpd/grules/users.grl
httpd.db.rules.events =  /usr/local/etc/uhppoted/httpd/grules/events.grl
httpd.db.rules.logs = /usr/local/etc/uhppoted/httpd/grules/logs.grl
httpd.audit.file = /usr/local/etc/uhppoted/httpd/audit/audit.log
; httpd.retention = 6h0m0s
; httpd.timezones =
httpd.with-pin = true


# DEVICES
UT0311-L0x.423137505.address = 192.168.1.157:60000
UT0311-L0x.423137505.door.1 = Top Door
UT0311-L0x.423137505.door.2 = Bottom Door
UT0311-L0x.423137505.door.3 = Unused
UT0311-L0x.423137505.door.4 = Unused
```

If I point it to an incorrect file via `--config` then it errors. if I update the http port to 8081, it also obliges. But, for some reason, it will not search for my device that I added here.

**Comment by uhppoted** [comment]
Hi,

_uhppoted-httpd_ doesn't use _uhppoted.conf_ for the devices. The controllers are actually stored in the `system/controllers.json` file if you really want to edit it manually but actually the controllers are managed from the user interface _System_ page:
- it will display any _discovered_ controllers
- use the **+** to add a controller if it hasn't been found by device discovery
- clear both the controller name and IP address to remove a controller

I'll make a note to remove the _Devices_ section from the compose _uhppoted.conf_.

**Comment by iKrushYou** [comment]
> Hi,
> 
> _uhppoted-httpd_ doesn't use _uhppoted.conf_ for the devices. The controllers are actually stored in the `system/controllers.json` file if you really want to edit it manually but actually the controllers are managed from the user interface _System_ page:
> 
> * it will display any _discovered_ controllers
> * use the **+** to add a controller if it hasn't been found by device discovery
> * clear both the controller name and IP address to remove a controller
> 
> I'll make a note to remove the _Devices_ section from the compose _uhppoted.conf_.

Oh awesome. Thanks for the quick response! I started with the rest interface that I think might have used that. 

I didn’t make it that far to see the configs in the UI as I couldn’t find the default user / pass. Is that documented anywhere?

**Comment by uhppoted** [comment]
&lt;smile&gt; *everything* except _uhppoted-httpd_ uses the _uhppoted.conf_ file so it was a fair assumption!

If you're using _docker compose_ then the default credentials are:
- user: _admin_
- password: _uhppoted_

The _docker compose_ stuff should probably do the same thing as the _daemon/service_ installer and generate a initial random admin password.

**Comment by uhppoted** [comment]
Going to close this - the immediate issue seems to be resolved and the enhancement is tracked in [docker compose: generate random admin user password on initial startup](https://github.com/uhppoted/uhppoted-httpd/issues/26).
