### ISSUE TITLE
docker compose: generate random admin user password on initial startup

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-httpd#26]
- https://github.com/uhppoted/uhppoted-httpd/issues/25
- https://github.com/uhppoted/uhppoted-httpd/discussions/41

Display _user setup_ page on start/login if there is no valid _admin_ user:
- [x] User setup page
- [x] Create _admin_ user iff does not exist
- [x] Check for admin user on startup
- [x] Remove admin user logic in _daemonize_
- [x] CHANGELOG
- [x] README

**Comment by twystd** [comment]
Closing as (provisionally) complete.
