### ISSUE TITLE
Manage cards without valid start/end dates

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-httpd#29]
Ref.:
   - [failed to update card](https://github.com/uhppoted/uhppoted-httpd/issues/27)
   - [show save / cancel buttons when user edits the From or To columns](https://github.com/uhppoted/uhppoted-httpd/issues/33)

The UHPPOTE controller only accepts cards with a valid start and end date but there is a valid use case for _uhppoted-httpd_ to allow a card to be created _ahead-of-time_ without a start or end date. Assigning a default start/end date is not a solution because it potentially allows a temporary card to have unexpected access.

- [x] Lowlight `incomplete` cards in the UI
- [x] Only load _valid'ish_ cards to the controller
- [x] ACL
- [x] Update simulator to reject cards without a valid start/end date
- [x] Add simulator REST API to create cards without valid start/end dates for testing
- [x] Configurable default start date ?
- [x] Configurable default end date ?

**Comment by twystd** [comment]
1. Added card from/to date zero value check to controller _put-card_ API
2. Added REST _put-card_ API to add/update cards from the REST API without the restrictions of the controller API.

Closing as completed, pending release v08.8.9.
