### ISSUE TITLE
[Enhancement] Cards | remove placeholder date for From and To inputs 

### ISSUE THREAD

**Issue by iKrushYou** [uhppoted/uhppoted-httpd#32]
This was extremely confusing to me as a user that these were not default values (see https://github.com/uhppoted/uhppoted-httpd/issues/27). Instead, these fields should have no placeholder or a placeholder that is blank like `mm/dd/yyyy` to signify that it is not automatically filled with a value 

Or, make the default value today. Because as it is currently, if you use the arrow keys it will act as if the value was null / 0. i.e. if you hit the up arrow on `2024` you get `0001` instead of `2025`

<img width="214" alt="image" src="https://github.com/uhppoted/uhppoted-httpd/assets/1500721/90a2b9d4-910d-4e8f-a235-df0f14841a9c">

Edit: I realize this is a Safari / WebKit issue. I just so happened to be using Chrome this time and see that it is not an issue / it is much more obvious the date isn't set

**Comment by uhppoted** [comment]
This was the best compromise found after experimenting across multiple browsers and multiple operating systems - the stock browser date/time controls are not great.

If you would like to replace them with a custom date/time control in your own version of the HTML it should be fairly straightforward.

**Comment by twystd** [comment]
Reopening to see if this Safari specific behaviour can be mitigated.

#### Notes

1. The placeholder attribute is [not mandated](https://html.spec.whatwg.org/multipage/input.html#input-type-attr-summary)
2. https://stackoverflow.com/questions/8430416/html5-date-field-and-placeholder-text-in-safari
3. https://community.weweb.io/t/how-to-prevent-safari-from-using-todays-date-as-placeholder-on-a-date-component/1721
4. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

#### Mitigations:
- [ ] Low light the from/to fields if the values are :invalid ?

**Comment by twystd** [comment]
Restyled card from/to date fields on Safari to dim fields if value is blank and no default start/end date is defined.

<img width="512" alt="screenshot 2024-09-04 at 10 26 15" src="https://github.com/user-attachments/assets/dfee7049-aadc-4098-8b0d-22cced51d606">

**Comment by twystd** [comment]
Added _onchange_ event handler to update style while editing.

Closing as completed, pending release v0.8.9.
