### ISSUE TITLE
[Enhancement] Cards | show save / cancel buttons when user edits the From or To columns 

### ISSUE THREAD

**Issue by iKrushYou** [uhppoted/uhppoted-httpd#33]
if you update the date columns in From or To, the save / cancel buttons do not appear as you'd expect from editing another field

**Comment by uhppoted** [comment]
I've just checked this on Chrome, Firefox and Safari and it seems to work ok on all of them. Can you provide more information?

**Comment by iKrushYou** [comment]
wow.. that is so strange. I am unable to reproduce this now. Sorry for the lack of information it was happening every time for me that it seemed straight forward 

now, when I edit the date it shows the check box

**Comment by uhppoted** [comment]
Ok, at a guess the Javascript hadn't loaded for some reason - if/when it happens again maybe check the developer console.

**Comment by iKrushYou** [comment]
I'll keep an eye out for that if it happens again 
sorry for the false alarm :)

**Comment by iKrushYou** [comment]
I was able to reproduce in safari. it happens when you crate a user with an invalid start/end date. Turns out this is because of the current date placeholders that don't tell you that there actually isn't a value there. it makes it very difficult to know what the issue is with the red row / dates 

https://github.com/uhppoted/uhppoted-httpd/assets/1500721/9c683a8f-00dd-40cb-acc0-0d8e40cbee2d

**Comment by uhppoted** [comment]
As far as I can tell, this was fixed along with https://github.com/uhppoted/uhppoted-httpd/issues/29 .. am going to close it. Feel free to reopen if you have further information.
