### ISSUE TITLE
[Bug] Cards | save button does not always update card group membership

### ISSUE THREAD

**Issue by iKrushYou** [uhppoted/uhppoted-httpd#36]
## Description

updating a card's group membership will sometimes not work if the only attribute changed is a group membership 

## Steps to reproduce
1. create a new card without any priviilges
<img width="808" alt="image" src="https://github.com/uhppoted/uhppoted-httpd/assets/1500721/5ea927e0-1827-4a09-9063-2268e5e973e4">
2. observe: the user is created without any privileges
<img width="982" alt="image" src="https://github.com/uhppoted/uhppoted-httpd/assets/1500721/f5aa90aa-67e4-4b9c-92af-2d829bb2d0d3">
<img width="990" alt="image" src="https://github.com/uhppoted/uhppoted-httpd/assets/1500721/60099a80-4023-434d-b64f-685d76e749af">
3. add a group to the card and hit the check mark to "save" 
4. observe: the "modified" corner is still present
5. observe: in the web controller, the doors still say forbid

notes:
- if you update the name of the user, it appears to save a lot quicker
- if you let the UI sit, eventually it seems to collect the changes and eventually persist them
- if you refresh the page, the changes might never be persisted to the controller 

I plan to give this to non-technical individuals and an issue like this could be extremely confusing / catastrophic for the adoption of a new interface

**Comment by uhppoted** [comment]
Probably related to [... warning messages I'm getting from my server...](https://github.com/uhppoted/uhppoted-httpd/discussions/34)

**Comment by iKrushYou** [comment]
> Probably related to [... warning messages I'm getting from my server...](https://github.com/uhppoted/uhppoted-httpd/discussions/34)

I believe this was indeed related

**Comment by uhppoted** [comment]
Am going to close this - there's nothing to really fix - but feel free to reopen if it becomes apparent that there is more to it than a network connectivity issue.
