### ISSUE TITLE
Deleting 'self' user remains logged in

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-httpd#42]
If the _admin_ user deletes their own user they remain logged in and until the cookie expires can log back in.

Rework so that:
- [x] Deleting _self_ logs out automatically
- [x] Deleting any user clears the cookies for that user
- [x] Cookie UIDs are checked against the current users list
- [x] Check what happens if the same user is logged in on e.g. two different browsers

**Comment by twystd** [comment]
- Added checks for user _is deleted_ to all authentication paths
- Cleared session cookies for users that are no longer valid
- A deleted user is automatically logged on on page refresh/timeout
- Posted a security notice in the README
- Notified any known users who might possibly be affected

Closing as (provisionally) completed.
