### ISSUE TITLE
UI is unusably slow with 100+ cards

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-httpd#43]
Ref. https://github.com/uhppoted/uhppoted-httpd/discussions/34#discussioncomment-10423271

With 100+ cards the user interface is sluggish to the point of being unusable:
- [x]  Cache element queries
- [x] Loading windmill
- [x] Optimise _rollback-all_ 
- [x] Optimised _commit-all_
- [x] _nightly_ builds
- [x] Optimise _grules_ evaluations
- [x] Incremental/paged load

**Comment by twystd** [comment]
Baseline performance with 200 cards: 
- page load: 14s

**Comment by twystd** [comment]
With basic '_querySelector_' cache:
<img width="655" alt="Screenshot 2024-09-09 at 11 04 06" src="https://github.com/user-attachments/assets/7ae7a283-5319-4cc7-9039-d28f5ce08ea6">
<img width="649" alt="Screenshot 2024-09-09 at 11 04 19" src="https://github.com/user-attachments/assets/ca6882e7-6d48-475f-82d6-5c412f7f5bd4">

**Comment by twystd** [comment]
Bug in _modified parent_ CSS selector is selecting all fields of all cards:
```
function modified(oid) {
    ...
   const list = document.querySelectorAll(`[data-oid^="${oid}."]`))
   ...
```

**Comment by twystd** [comment]
With cached _query_ and _query modified_:
<img width="555" alt="Screenshot 2024-09-10 at 11 38 32" src="https://github.com/user-attachments/assets/732055c3-a72a-4765-88fe-9197d31a2f65">

**Comment by twystd** [comment]
_revert-all_:

<img width="452" alt="Screenshot 2024-09-13 at 09 28 29" src="https://github.com/user-attachments/assets/2df836b1-26e1-46e9-adfd-52fbbe6c7d62">

**Comment by twystd** [comment]
_rollback-all_ (with caching):

<img width="459" alt="Screenshot 2024-09-13 at 10 40 39" src="https://github.com/user-attachments/assets/5f4518ef-e17a-4293-af61-b82c44250c1b">

**Comment by twystd** [comment]
_rollback-all_ (modified only):
<img width="469" alt="Screenshot 2024-09-13 at 10 58 30" src="https://github.com/user-attachments/assets/716f5592-2a88-4e54-a29c-f5ead47bd70a">

**Comment by twystd** [comment]
With UI optimizations:
<img width="432" alt="Screenshot 2024-09-20 at 12 16 46" src="https://github.com/user-attachments/assets/902264dc-8d50-47c7-bb96-b17b76b9cb0c">

Network call is now the bottleneck.

**Comment by twystd** [comment]
Slow network call is the consequence of evaluating _grules_ for the 1000+ objects that make up the cards list for 200+ cards:

- [ ] cache _grules_ evaluations
- [ ] clear cache on grules reload
- [ ] clear cache on user login
- [ ] clear cache on user logout
- [ ] clear cache on user delete
- [ ] optionally disable _grules_ in _uhppoted.conf_

**Comment by twystd** [comment]
Caching grules _CanView_ evaluations reduces initial network call to 600ms and subsequent calls to 50ms. Initial load time is now below 2s.

<img width="399" alt="Screenshot 2024-09-24 at 10 39 47" src="https://github.com/user-attachments/assets/91b185e1-c560-4365-ac21-b1ea124924a8">

**Comment by uhppoted** [comment]
Implemented _prefetch_ on page load to fetch first page of cards:

<img width="447" alt="Screenshot 2024-10-01 at 11 24 30" src="https://github.com/user-attachments/assets/13d13de2-2c86-4165-bc5c-bb7c21b2127c">
<img width="419" alt="Screenshot 2024-10-01 at 11 25 03" src="https://github.com/user-attachments/assets/699267c3-a964-4eeb-9b8c-a80cf2d54d11">
<img width="568" alt="Screenshot 2024-10-01 at 11 26 08" src="https://github.com/user-attachments/assets/8989674b-a93f-4101-9b71-b15830438301">

**Comment by uhppoted** [comment]
Initial time to load reduced to ~500ms - closing this as '_good enough for now_' and deferring virtual lists to a separate issue (https://github.com/uhppoted/uhppoted-httpd/issues/45).
