### ISSUE TITLE
Not able to add "admin" when using Docker with Synology NAS 

### ISSUE THREAD

**Issue by sepalab** [uhppoted/uhppoted-httpd#46]
Hello,
all starts well, see in the logs the scan of the controller and the lists updated but I cannot pass from the admin page.

Not able to get around that. Anyone with insights that how can I go around this? 
Or is it a bug?

Thanks,
//Alcides

**Comment by sepalab** [comment]
Hello,
thanks for the quick reply.
Answers below:
1- Yes. The initial page;
2- Tested in Edge and Firefox;
3- Yes;
4- No message; 
5- Console from Docker, it seems all start well:
2024/10/17 14:19:43 uhppoted-httpd service v0.8.9 - Linux (PID 1)
2024/10/17 14:19:44 INFO   HTTPD    HTTP  server starting on port :8080
2024/10/17 14:19:47 INFO   Adding unconfigured controller 225088461
2024/10/17 14:19:47 INFO   system   Sweeping all items invalidated before 2024-10-17 08:19:47
2024/10/17 14:19:47 INFO   ACL 225088461  unchanged:0   updated:0   added:0   deleted:0  
2024/10/17 14:19:47 INFO   ACL compare    unchanged:0   updated:0   added:0   deleted:0  
2024/10/17 14:20:17 INFO   225088461: refreshing LAN controller status
2024/10/17 14:20:17 INFO   225088461: retrieving LAN controller events ([{8 4294967295}])
2024/10/17 14:20:17 INFO   system   Sweeping all items invalidated before 2024-10-17 08:20:17
2024/10/17 14:20:17 INFO   ACL 225088461  unchanged:0   updated:0   added:0   deleted:0  
2024/10/17 14:20:17 INFO   ACL compare    unchanged:0   updated:0   added:0   deleted:0  
2024/10/17 14:20:47 INFO   225088461: refreshing LAN controller status
2024/10/17 14:20:47 INFO   225088461: retrieving LAN controller events ([{8 4294967295}])
2024/10/17 14:20:47 INFO   system   Sweeping all items invalidated before 2024-10-17 08:20:47
2024/10/17 14:20:47 INFO   ACL 225088461  unchanged:0   updated:0   added:0   deleted:0  
2024/10/17 14:20:47 INFO   ACL compare    unchanged:0   updated:0   added:0   deleted:0  

Cheers,
//Alcides

**Comment by uhppoted** [comment]
Ooof, well that's embarrassing - a fix for an obscure edge case a couple of weeks back introduced a typo into the setup logic. Sorry about that :-(.

I've pushed the fix to the repo and also updated the _ghcr_ Docker image - if you pull the latest you should (hopefully) be good to go.

**Comment by sepalab** [comment]
Hello,
it worked.

Thanks,
//Alcides
