### ISSUE TITLE
raspberrypi installation

### ISSUE THREAD

**Issue by taufpate** [uhppoted/uhppoted-httpd#5]
did anyone has build for raspberry pi? i'm having a lot of problems :-(

When i try to make build return:` 'OptionParser::InvalidOption: invalid option: --no-source-map'`  but i have Sass 3.7.4 installed

If i remove --no-source-map param in makefile  the give me this error: 
`'Errno::EISDIR: Is a directory @ io_fread - sass/themes/light'`

if i remove all sass compilation lines then:

```
ESLint couldn't find the config "standard" to extend from. Please check that the name of the config is correct.

The config "standard" was referenced from the config file in "/home/pi/Desktop/uhppoted-httpd/.eslintrc.js".
```

and if y try unsing 'Without using make' version, go build -trimpath -o bin ./... returns
`go: cannot write multiple packages to non-directory bin`

**Comment by uhppoted** [comment]
Hmm, have only ever built this on Ubuntu 22.04, Windows and MacOS never on a Pi - will try to set up one up the next day or so to check.

But to get you over the immediate issues:
- the repo includes the CSS (in the [httpd/html](https://github.com/uhppoted/uhppoted-httpd/tree/master/httpd/html) folder) so you don't need to run _Sass_ unless you've changed something.
- likewise, _eslint_ is a sanity check for development so you can remove it from the Makefile build target (or alternatively install [eslint-config-standard](https://www.npmjs.com/package/eslint-config-standard)
- `go: cannot write multiple packages to non-directory bin` means that `bin` is a file not a directory - probably created by a previous build. Try deleting it and then creating the directory before you run the _go build..._ command

The `build` target in the _Makefile_ to build just the bare minimum will then look like:
```
build: format
	mkdir -p bin
	go build -trimpath -o bin ./...
```
or, not using _make_:
```
rm -rf bin
mkdir -p bin
go fmt ./...
go build -trimpath -o bin ./...
```

**Comment by uhppoted** [comment]
Ok, mystery solved:

`apt install sass` on Ubuntu/Debian/Raspbian seems to install `ruby-sass` which was obsoleted in 2019 (see https://sass-lang.com/ruby-sass). You can either install the latest and greatest (installation instructions [here](https://sass-lang.com/install)) or just remove it from the build commands if you're not modifying the CSS in any way.

The _build instructions_ in the README have been updated to include:
- [eslint-config-standard](https://www.npmjs.com/package/eslint-config-standard)
- creating the _bin_ directory if you're not using _make_
- a note about `ruby-sass`

**Comment by uhppoted** [comment]
Added some [preliminary documentation](https://github.com/uhppoted/uhppoted-httpd/tree/master/documentation) on the folder structure and runtime files.

Going to close this - feel free to reopen if you need additional information :-).
