### ISSUE TITLE
default auth doesn't work

### ISSUE THREAD

**Issue by YBonline** [uhppoted/uhppoted-httpd#6]
The default username of admin password of uhppoted doesn't seem to work. In the auth.json file the users array is generated as empty and there doesn't seem to be documentation of how to create a user account, how do you do that? thank you!

**Comment by uhppoted** [comment]
Can you describe how you installed it?

If you installed it via the _daemonize_ command there should have been an install message that looked something like:
```
    Do you want to create a default 'admin' user (yes/no)? yes

   ... creating default 'admin' user
   ... created default 'admin' user, password:ss7eR8PBi83wSE0P
```
and the `admin` user would have been created in the _users.json_ file (_.../var/.../httpd/system/users.json_).

If all else fails, you could override the _users.json_ file with an _auth.json_ user taken from the quickstarts:
```
 "users": {
    "admin": {
      "salt": "3606c608288dc36c3612c7f8a05870aa",
      "password": "5fbccbe2b815528b7bc3f2e5a1b7c6fb6b8ba418d84e11b1e7ffee02c951880f",
      "role": "admin"
    }
  },
 ...
```

**Comment by YBonline** [comment]
I upgraded from an old version and ran daemonize, I might have tried before earlier in development, but it didn't give me that prompt while running daemonize. After deleting users.json and running it again it did give me a username and password that works, so I'll close this issue.

I did try putting that user in auth.json prior to creating this issue, but that didn't work for the listed default of admin / uhppoted FYI, still said incorrect username/password

**Comment by uhppoted** [comment]
Ah, ok, that makes sense - if you have an existing installation _daemonize_ keeps any existing files and wouldn't create a new default user. Bit weird that it deleted the existing _admin_ user though - I'll dig into that a bit and see if there's something in the logic.

Thanks for the info - I honestly thought I was the only person using this thing so have been a bit cavalier about shuffling stuff around :-).

**Comment by YBonline** [comment]
There was an existing entry for the admin user in users.json but I never saw it list a password, so I don't think it  deleted the existing admin user, just at some previous point in time it created it without telling me. The only mystery is auth.json doesn't seem to override the users.json from my brief testing, if its supposed to. I tried to use it a while ago and it was fairly incomplete so I'm not actually using it yet, just trying it out to see where its at. It looks like a very exciting project and there is a lot of potential to have real open source controllers for access control systems, something severely lacking amongst the access control industry.
