### ISSUE TITLE
Unable to run as service on RPI.

### ISSUE THREAD

**Issue by KingSteve032** [uhppoted/uhppoted-httpd#7]
I'm unable to run this as a service. This is the error I get when trying so. When running it with the normal ./uhppoted-httpd --console command it runs fine but when running it as that the default login does not work.

Jul 05 16:06:11 itisasecret systemd[1]: Started UHPPOTE UTO311-L0x access card controllers HTTPD service/daemon.
Jul 05 16:06:11 itisasecret uhppoted-httpd[1685]: 2022/07/05 16:06:11 uhppoted-httpd service v0.8.0 - Linux (PID 1685)
Jul 05 16:06:11 itisasecret uhppoted-httpd[1685]: ERROR: Error checking PID lockfile '/var/uhppoted/uhppoted-httpd.pid' (stat /var/uhppoted/uhppoted-httpd.pid: permission denied)
Jul 05 16:06:11 itisasecret systemd[1]: uhppoted-httpd.service: Main process exited, code=exited, status=1/FAILURE
Jul 05 16:06:11 itisasecret systemd[1]: uhppoted-httpd.service: Failed with result 'exit-code'.

**Comment by uhppoted** [comment]
Hi,

I'm going to go out on a limb and guess that you were running it in console mode as _root_ which means there's a good chance the _/var/uhppoted_ folder and/or the _/var/uhppoted/uhppoted-httpd.pid_ file are owned by root. By default the service runs under the account _uhppoted_ so it may not have write permissions to either _/var/uhppoted_ or _/var/uhppoted/uhppoted-httpd.pid_

1. Check the permissions on _/var/uhppoted_:
```
sudo ls -la /var | grep uhppoted
```

2. Check the permissions on _/var/uhppoted/uhppoted-httpd.pid_:
```
sudo ls -la /var/uhppoted/uhppoted-httpd.pid
```
In  both cases the user:group should be uhppoted:uhppoted i.e. something like:
```
drwxr-xr-x  10 uhppoted  uhppoted  320 Jul  4 11:24 uhppoted
drwxr-xr-x  10 uhppoted  uhppoted  320 Jul  4 11:24 /var/uhppoted/uhppoted-httpd.pid
```
If not you need to update the permissions:
```
sudo chown -R uhppoted:uhppoted /var/uhppoted
```
You may also need to update the permissions on /etc/uhppoted:
```
sudo chown -R uhppoted:uhppoted /etc/uhppoted
```

If that doesn't solve the problem let me know and I'll dig into a bit more.

**Comment by KingSteve032** [comment]
Yep I that fixed it. Thank you!
