### ISSUE TITLE
Display the generated admin user/password as the last step of daemonize

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-httpd#9]
The admin user ID and password generated during _daemonize_ is frequently overlooked (?) because it's buried in amongst all the other information.

Display it a bit more prominently as the last piece of information.

- cf. [default auth doesn't work](https://github.com/uhppoted/uhppoted-httpd/issues/6)
- cf.  https://github.com/uhppoted/uhppoted/discussions/13#discussioncomment-3132084

**Comment by twystd** [comment]
(pending release)

**Comment by uhppoted** [comment]
Fixed in [release v0.8.1](https://github.com/uhppoted/uhppoted-httpd/releases/tag/v0.8.1)
